<?php
declare(strict_types=1);

use Migrations\BaseMigration;

class InitialHomeHealthSchema extends BaseMigration
{
    public function change(): void
    {
        $this->table('users')
            ->addColumn('full_name', 'string', ['limit' => 120])
            ->addColumn('email', 'string', ['limit' => 160])
            ->addColumn('password_hash', 'string', ['limit' => 255])
            ->addColumn('role', 'string', ['limit' => 60])
            ->addColumn('mobile', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('status', 'string', ['limit' => 30, 'default' => 'active'])
            ->addColumn('mfa_enabled', 'boolean', ['default' => false])
            ->addColumn('last_login_at', 'datetime', ['null' => true])
            ->addTimestamps('created', 'modified')
            ->addIndex(['email'], ['unique' => true])
            ->create();

        $this->table('patients')
            ->addColumn('first_name', 'string', ['limit' => 120])
            ->addColumn('last_name', 'string', ['limit' => 120])
            ->addColumn('dob', 'date')
            ->addColumn('gender', 'string', ['limit' => 20, 'null' => true])
            ->addColumn('medicare_number', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('insurance_member_id', 'string', ['limit' => 60, 'null' => true])
            ->addColumn('phone', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('address1', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('address2', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('city', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('state', 'string', ['limit' => 12, 'null' => true])
            ->addColumn('postal_code', 'string', ['limit' => 20, 'null' => true])
            ->addColumn('emergency_contact_name', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('emergency_contact_relationship', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('emergency_contact_phone', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('payer_type', 'string', ['limit' => 40])
            ->addColumn('primary_physician', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('responsible_party_name', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('responsible_party_relationship', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('responsible_party_phone', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('status', 'string', ['limit' => 40, 'default' => 'active'])
            ->addTimestamps('created', 'modified')
            ->create();

        $this->table('referrals')
            ->addColumn('patient_id', 'integer')
            ->addColumn('source_name', 'string', ['limit' => 160])
            ->addColumn('admission_source', 'string', ['limit' => 60, 'null' => true])
            ->addColumn('payer_type', 'string', ['limit' => 40])
            ->addColumn('primary_diagnosis', 'string', ['limit' => 255])
            ->addColumn('requested_disciplines', 'text', ['null' => true])
            ->addColumn('order_status', 'string', ['limit' => 40, 'default' => 'pending'])
            ->addColumn('physician_orders_signed', 'boolean', ['default' => false])
            ->addColumn('physician_orders_signed_at', 'datetime', ['null' => true])
            ->addColumn('face_to_face_date', 'date', ['null' => true])
            ->addColumn('referring_provider_name', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('referring_provider_phone', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('pcp_name', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('pcp_phone', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('caregiver_name', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('caregiver_relationship', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('caregiver_phone', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('service_location_type', 'string', ['limit' => 60, 'null' => true])
            ->addColumn('service_address1', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('service_city', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('service_state', 'string', ['limit' => 12, 'null' => true])
            ->addColumn('service_postal_code', 'string', ['limit' => 20, 'null' => true])
            ->addColumn('intake_ready', 'boolean', ['default' => false])
            ->addColumn('planned_soc_date', 'date')
            ->addColumn('status', 'string', ['limit' => 40, 'default' => 'received'])
            ->addColumn('notes', 'text', ['null' => true])
            ->addColumn('created_by', 'integer', ['null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('patient_id', 'patients')
            ->create();

        $this->table('referral_documents')
            ->addColumn('referral_id', 'integer')
            ->addColumn('document_type', 'string', ['limit' => 60])
            ->addColumn('document_status', 'string', ['limit' => 40, 'default' => 'requested'])
            ->addColumn('source_name', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('received_at', 'datetime', ['null' => true])
            ->addColumn('signed_at', 'datetime', ['null' => true])
            ->addColumn('original_file_name', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('stored_file_name', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('mime_type', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('file_size', 'integer', ['null' => true])
            ->addColumn('attachment_path', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('document_note', 'text', ['null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('referral_id', 'referrals')
            ->create();

        $this->table('episodes')
            ->addColumn('patient_id', 'integer')
            ->addColumn('referral_id', 'integer', ['null' => true])
            ->addColumn('cert_start_date', 'date')
            ->addColumn('cert_end_date', 'date')
            ->addColumn('start_of_care_date', 'date', ['null' => true])
            ->addColumn('episode_status', 'string', ['limit' => 40])
            ->addColumn('payer_type', 'string', ['limit' => 40])
            ->addColumn('primary_diagnosis', 'string', ['limit' => 255])
            ->addColumn('admission_readiness_snapshot', 'text', ['null' => true])
            ->addColumn('noa_due_date', 'date', ['null' => true])
            ->addColumn('pdgm_group_code', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('oasis_version_required', 'string', ['limit' => 40, 'null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('patient_id', 'patients')
            ->addForeignKey('referral_id', 'referrals')
            ->create();

        $this->table('episode_periods')
            ->addColumn('episode_id', 'integer')
            ->addColumn('period_number', 'integer')
            ->addColumn('period_start_date', 'date')
            ->addColumn('period_end_date', 'date')
            ->addColumn('hipps_code', 'string', ['limit' => 60, 'null' => true])
            ->addColumn('status', 'string', ['limit' => 40, 'default' => 'open'])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('episode_id', 'episodes')
            ->create();

        $this->table('physician_orders')
            ->addColumn('referral_id', 'integer', ['null' => true])
            ->addColumn('episode_id', 'integer')
            ->addColumn('referral_document_id', 'integer', ['null' => true])
            ->addColumn('order_scope', 'string', ['limit' => 60])
            ->addColumn('version_number', 'integer', ['default' => 1])
            ->addColumn('order_status', 'string', ['limit' => 40, 'default' => 'draft'])
            ->addColumn('active', 'boolean', ['default' => true])
            ->addColumn('sent_at', 'datetime', ['null' => true])
            ->addColumn('received_at', 'datetime', ['null' => true])
            ->addColumn('signed_at', 'datetime', ['null' => true])
            ->addColumn('signer_name', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('order_summary', 'text', ['null' => true])
            ->addColumn('order_note', 'text', ['null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('referral_id', 'referrals')
            ->addForeignKey('episode_id', 'episodes')
            ->addForeignKey('referral_document_id', 'referral_documents')
            ->create();

        $this->table('assessments')
            ->addColumn('episode_id', 'integer')
            ->addColumn('assessment_type', 'string', ['limit' => 60])
            ->addColumn('completed_at', 'datetime')
            ->addColumn('oasis_version', 'string', ['limit' => 40])
            ->addColumn('status', 'string', ['limit' => 40])
            ->addColumn('principal_diagnosis_code', 'string', ['limit' => 40])
            ->addColumn('functional_score', 'integer', ['default' => 0])
            ->addColumn('comorbidity_level', 'string', ['limit' => 40, 'default' => 'none'])
            ->addColumn('medication_reconciliation_completed', 'boolean', ['default' => false])
            ->addColumn('homebound_status', 'string', ['limit' => 60, 'null' => true])
            ->addColumn('homebound_narrative', 'text', ['null' => true])
            ->addColumn('fall_risk_level', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('hospitalization_risk', 'string', ['limit' => 40, 'null' => true])
            ->addColumn('emergency_preparedness_reviewed', 'boolean', ['default' => false])
            ->addColumn('care_plan_goals', 'text', ['null' => true])
            ->addColumn('clinical_summary', 'text', ['null' => true])
            ->addColumn('assessment_payload', 'text', ['null' => true])
            ->addColumn('answers', 'text', ['null' => true])
            ->addColumn('created_by', 'integer', ['null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('episode_id', 'episodes')
            ->create();

        $this->table('visits')
            ->addColumn('episode_id', 'integer')
            ->addColumn('patient_id', 'integer')
            ->addColumn('visit_type', 'string', ['limit' => 60])
            ->addColumn('discipline', 'string', ['limit' => 60])
            ->addColumn('scheduled_start', 'datetime')
            ->addColumn('scheduled_end', 'datetime')
            ->addColumn('actual_start', 'datetime', ['null' => true])
            ->addColumn('actual_end', 'datetime', ['null' => true])
            ->addColumn('clinician_name', 'string', ['limit' => 160])
            ->addColumn('status', 'string', ['limit' => 40, 'default' => 'scheduled'])
            ->addColumn('requires_evv', 'boolean', ['default' => false])
            ->addColumn('documentation_summary', 'text', ['null' => true])
            ->addColumn('documentation_status', 'string', ['limit' => 40, 'default' => 'pending'])
            ->addColumn('documentation_payload', 'text', ['null' => true])
            ->addColumn('qa_review_notes', 'text', ['null' => true])
            ->addColumn('reassigned_from_clinician', 'string', ['limit' => 160, 'null' => true])
            ->addColumn('missed_reason', 'text', ['null' => true])
            ->addColumn('follow_up_plan', 'text', ['null' => true])
            ->addColumn('sync_status', 'string', ['limit' => 40, 'default' => 'synced'])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('episode_id', 'episodes')
            ->addForeignKey('patient_id', 'patients')
            ->create();

        $this->table('check_in_out_events')
            ->addColumn('visit_id', 'integer')
            ->addColumn('event_type', 'string', ['limit' => 40])
            ->addColumn('event_time', 'datetime')
            ->addColumn('latitude', 'decimal', ['precision' => 10, 'scale' => 7, 'null' => true])
            ->addColumn('longitude', 'decimal', ['precision' => 10, 'scale' => 7, 'null' => true])
            ->addColumn('accuracy_meters', 'integer', ['null' => true])
            ->addColumn('device_metadata', 'text', ['null' => true])
            ->addColumn('source', 'string', ['limit' => 40, 'default' => 'mobile_web'])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('visit_id', 'visits')
            ->create();

        $this->table('evv_records')
            ->addColumn('visit_id', 'integer')
            ->addColumn('state_code', 'string', ['limit' => 10])
            ->addColumn('vendor_name', 'string', ['limit' => 120])
            ->addColumn('status', 'string', ['limit' => 40, 'default' => 'pending_submission'])
            ->addColumn('payload', 'text', ['null' => true])
            ->addColumn('exception_reason', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('submitted_at', 'datetime', ['null' => true])
            ->addColumn('submission_reference', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('reconciled_at', 'datetime', ['null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('visit_id', 'visits')
            ->create();

        $this->table('claims')
            ->addColumn('episode_id', 'integer')
            ->addColumn('claim_type', 'string', ['limit' => 40])
            ->addColumn('billing_period_start', 'date', ['null' => true])
            ->addColumn('billing_period_end', 'date', ['null' => true])
            ->addColumn('status', 'string', ['limit' => 40, 'default' => 'draft'])
            ->addColumn('amount', 'decimal', ['precision' => 10, 'scale' => 2, 'null' => true])
            ->addColumn('hold_reason', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('submission_reference', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('submitted_at', 'datetime', ['null' => true])
            ->addColumn('payer_claim_number', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('accepted_at', 'datetime', ['null' => true])
            ->addColumn('rejected_at', 'datetime', ['null' => true])
            ->addColumn('rejection_reason', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('payment_amount', 'decimal', ['precision' => 10, 'scale' => 2, 'null' => true])
            ->addColumn('remittance_reference', 'string', ['limit' => 80, 'null' => true])
            ->addColumn('paid_at', 'datetime', ['null' => true])
            ->addColumn('voided_at', 'datetime', ['null' => true])
            ->addColumn('void_reason', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('corrected_from_claim_id', 'integer', ['null' => true])
            ->addColumn('correction_reason', 'string', ['limit' => 255, 'null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('episode_id', 'episodes')
            ->create();

        $this->table('qa_tasks')
            ->addColumn('episode_id', 'integer', ['null' => true])
            ->addColumn('visit_id', 'integer', ['null' => true])
            ->addColumn('assessment_id', 'integer', ['null' => true])
            ->addColumn('task_type', 'string', ['limit' => 60])
            ->addColumn('priority', 'string', ['limit' => 20, 'default' => 'medium'])
            ->addColumn('status', 'string', ['limit' => 20, 'default' => 'open'])
            ->addColumn('title', 'string', ['limit' => 160])
            ->addColumn('details', 'text', ['null' => true])
            ->addColumn('assigned_role', 'string', ['limit' => 60, 'null' => true])
            ->addColumn('assigned_user_name', 'string', ['limit' => 120, 'null' => true])
            ->addColumn('assigned_at', 'datetime', ['null' => true])
            ->addColumn('assignment_history', 'text', ['null' => true])
            ->addColumn('escalation_note', 'text', ['null' => true])
            ->addColumn('last_escalated_at', 'datetime', ['null' => true])
            ->addColumn('due_at', 'datetime', ['null' => true])
            ->addTimestamps('created', 'modified')
            ->addForeignKey('episode_id', 'episodes')
            ->addForeignKey('visit_id', 'visits')
            ->addForeignKey('assessment_id', 'assessments')
            ->create();

        $this->table('audit_events')
            ->addColumn('actor_email', 'string', ['limit' => 160])
            ->addColumn('action', 'string', ['limit' => 80])
            ->addColumn('model', 'string', ['limit' => 80])
            ->addColumn('model_id', 'integer')
            ->addColumn('details', 'text', ['null' => true])
            ->addColumn('created', 'datetime', ['default' => 'CURRENT_TIMESTAMP'])
            ->create();

        $this->table('app_settings')
            ->addColumn('require_mfa', 'boolean', ['default' => false])
            ->addColumn('session_timeout_minutes', 'integer', ['default' => 30])
            ->addColumn('remember_device_days', 'integer', ['default' => 14])
            ->addColumn('password_rotation_days', 'integer', ['default' => 90])
            ->addColumn('attachment_retention_days', 'integer', ['default' => 365])
            ->addColumn('allowed_ip_ranges', 'text', ['null' => true])
            ->addColumn('enforce_device_attestation', 'boolean', ['default' => false])
            ->addTimestamps('created', 'modified')
            ->create();
    }
}
