import type { AppDataset, AppUser, Assessment, AuditEvent, Claim, Episode, EvvRecord, Patient, PhysicianOrder, QaTask, Referral, ReferralDocument, SecuritySettings, SessionActivity, Visit } from './types'

const patients: Patient[] = [
  {
    id: 1,
    first_name: 'Eleanor',
    last_name: 'Bishop',
    dob: '1946-02-14',
    gender: 'Female',
    medicare_number: '1EG4TE5MK73',
    insurance_member_id: '1EG4TE5MK73',
    payer_type: 'Medicare',
    phone: '404-555-0101',
    address1: '125 Peachtree View',
    city: 'Atlanta',
    state: 'GA',
    postal_code: '30309',
    emergency_contact_name: 'Samuel Bishop',
    emergency_contact_relationship: 'Spouse',
    emergency_contact_phone: '404-555-0110',
    status: 'active',
    primary_physician: 'Dr. Hayes',
    responsible_party_name: 'Samuel Bishop',
    responsible_party_relationship: 'Spouse',
    responsible_party_phone: '404-555-0110',
  },
]

const referrals: Referral[] = [
  {
    id: 1,
    patient_id: 1,
    patient_name: 'Eleanor Bishop',
    source_name: 'Northside Hospital',
    admission_source: 'Hospital discharge',
    payer_type: 'Medicare',
    primary_diagnosis: 'I50.32 Chronic diastolic heart failure',
    requested_disciplines: ['SN', 'PT'],
    order_status: 'signed',
    physician_orders_signed: true,
    physician_orders_signed_at: '2026-04-16 14:30:00',
    face_to_face_date: '2026-04-15',
    referring_provider_name: 'Dr. Alexis Monroe',
    referring_provider_phone: '404-555-0133',
    pcp_name: 'Dr. Hayes',
    pcp_phone: '404-555-0144',
    caregiver_name: 'Samuel Bishop',
    caregiver_relationship: 'Spouse',
    caregiver_phone: '404-555-0110',
    service_location_type: 'Patient home',
    service_address1: '125 Peachtree View',
    service_city: 'Atlanta',
    service_state: 'GA',
    service_postal_code: '30309',
    planned_soc_date: '2026-04-19',
    intake_ready: true,
    status: 'accepted',
  },
]

const referralDocuments: ReferralDocument[] = [
  {
    id: 1,
    referral_id: 1,
    document_type: 'face_to_face',
    document_status: 'received',
    source_name: 'Northside discharge packet',
    received_at: '2026-04-15 13:00:00',
    original_file_name: 'face-to-face-note.pdf',
    mime_type: 'application/pdf',
    file_size: 182944,
    document_note: 'Face-to-face encounter included in the hospital packet.',
  },
  {
    id: 2,
    referral_id: 1,
    document_type: 'physician_orders',
    document_status: 'signed',
    source_name: 'Dr. Alexis Monroe fax',
    received_at: '2026-04-16 10:00:00',
    signed_at: '2026-04-16 14:30:00',
    original_file_name: 'signed-physician-orders.pdf',
    mime_type: 'application/pdf',
    file_size: 244210,
    document_note: 'Signed physician orders scanned into intake review.',
  },
]

const episodes: Episode[] = [
  {
    id: 1,
    patient_id: 1,
    patient_name: 'Eleanor Bishop',
    referral_id: 1,
    cert_start_date: '2026-04-19',
    cert_end_date: '2026-06-17',
    start_of_care_date: '2026-04-19',
    episode_status: 'active',
    payer_type: 'Medicare',
    primary_diagnosis: 'I50.32 Chronic diastolic heart failure',
    admission_readiness_snapshot: {
      referral_source: 'Northside Hospital',
      admission_source: 'Hospital discharge',
      planned_soc_date: '2026-04-19',
      face_to_face_date: '2026-04-15',
      primary_diagnosis: 'I50.32 Chronic diastolic heart failure',
      requested_disciplines: ['SN', 'PT'],
      order_status: 'signed',
      physician_orders_signed: true,
      physician_orders_signed_at: '2026-04-16 14:30:00',
      referring_provider_name: 'Dr. Alexis Monroe',
      referring_provider_phone: '404-555-0133',
      pcp_name: 'Dr. Hayes',
      pcp_phone: '404-555-0144',
      caregiver_name: 'Samuel Bishop',
      caregiver_relationship: 'Spouse',
      caregiver_phone: '404-555-0110',
      service_location_type: 'Patient home',
      service_address1: '125 Peachtree View',
      service_city: 'Atlanta',
      service_state: 'GA',
      service_postal_code: '30309',
      notes: 'Hospital discharge referral ready for SOC.',
    },
    noa_due_date: '2026-04-24',
    pdgm_group_code: 'MMTA-CARDIAC-EARLY-MEDIUM-LOW',
    oasis_version_required: 'OASIS-E2',
  },
]

const physicianOrders: PhysicianOrder[] = [
  {
    id: 1,
    referral_id: 1,
    episode_id: 1,
    referral_document_id: 2,
    order_scope: 'admission',
    version_number: 1,
    order_status: 'signed',
    active: true,
    received_at: '2026-04-16 10:00:00',
    signed_at: '2026-04-16 14:30:00',
    signer_name: 'Dr. Alexis Monroe',
    order_summary: 'Admission physician order packet for planned SOC on 2026-04-19.',
    order_note: 'Initial admission order packet signed and ready for SOC activation.',
  },
]

const assessments: Assessment[] = [
  {
    id: 1,
    episode_id: 1,
    assessment_type: 'soc',
    completed_at: '2026-04-19 09:30:00',
    oasis_version: 'OASIS-E2',
    status: 'final',
    principal_diagnosis_code: 'I50.32',
    functional_score: 14,
    comorbidity_level: 'low',
    medication_reconciliation_completed: true,
    homebound_status: 'homebound',
    homebound_narrative: 'Patient leaves home only for medical appointments and requires caregiver support to do so safely.',
    fall_risk_level: 'moderate',
    hospitalization_risk: 'elevated',
    emergency_preparedness_reviewed: true,
    care_plan_goals: 'Prevent heart failure exacerbation, improve safe mobility, and reinforce medication adherence.',
    clinical_summary: 'SOC assessment finalized with medication reconciliation, homebound documentation, caregiver teaching, and safety review.',
    answers: {
      M0110: '1',
      M1033: '1',
      M1860: '3',
      M2020: '2',
    },
    assessment_payload: {
      medication_review: {
        issues: 'Reviewed daily weights, sodium limits, and Lasix timing with spouse.',
        high_risk_meds: 'Diuretics monitored for adherence and dizziness.',
      },
      wounds: {
        present: false,
        notes: 'No open wounds observed at SOC.',
      },
      caregiver_support: {
        availability: 'Spouse available daily',
        notes: 'Caregiver assists with medication reminders and transportation.',
      },
      risk_notes: 'Needs close monitoring for dyspnea, edema, and fatigue during the first week.',
    },
  },
]

const visits: Visit[] = [
  {
    id: 1,
    episode_id: 1,
    patient_id: 1,
    patient_name: 'Eleanor Bishop',
    visit_type: 'soc',
    discipline: 'SN',
    scheduled_start: '2026-04-19 09:00:00',
    scheduled_end: '2026-04-19 10:00:00',
    actual_start: '2026-04-19 09:02:00',
    actual_end: '2026-04-19 09:58:00',
    clinician_name: 'Nina Clinician',
    status: 'completed',
    requires_evv: true,
    documentation_summary: 'Completed SOC visit, medication reconciliation, and safety review.',
    sync_status: 'synced',
  },
  {
    id: 2,
    episode_id: 1,
    patient_id: 1,
    patient_name: 'Eleanor Bishop',
    visit_type: 'routine',
    discipline: 'PT',
    scheduled_start: '2026-04-21 11:00:00',
    scheduled_end: '2026-04-21 11:45:00',
    clinician_name: 'Miles Therapy',
    status: 'scheduled',
    requires_evv: true,
    sync_status: 'synced',
  },
]

const evvRecords: EvvRecord[] = [
  {
    id: 1,
    visit_id: 1,
    state_code: 'GA',
    vendor_name: 'Georgia EVV Sandbox',
    status: 'submitted',
    submitted_at: '2026-04-19 10:05:00',
  },
]

const claims: Claim[] = [
  {
    id: 1,
    episode_id: 1,
    claim_type: 'noa',
    status: 'draft',
  },
  {
    id: 2,
    episode_id: 1,
    claim_type: 'episode',
    status: 'draft',
    amount: 2480,
    hold_reason: 'Awaiting QA sign-off and EVV reconciliation.',
  },
]

const qaTasks: QaTask[] = [
  {
    id: 1,
    episode_id: 1,
    assessment_id: 1,
    task_type: 'oasis_review',
    priority: 'high',
    status: 'open',
    title: 'Validate OASIS-E2 and coding',
    details: 'Confirm diagnosis coding, medication review, and homebound narrative.',
    assigned_role: 'QA',
    assigned_user_name: 'Quinn QA Reviewer',
    assigned_at: '2026-04-20 08:00:00',
    assignment_history: [
      {
        timestamp: '2026-04-20 08:00:00',
        action: 'assigned',
        by: 'Marina Intake',
        from: 'Unassigned',
        to: 'Quinn QA Reviewer (QA)',
      },
      {
        timestamp: '2026-04-21 09:15:00',
        action: 'escalated',
        by: 'Bianca Billing',
        owner: 'Quinn QA Reviewer (QA)',
        note: 'Claim release is waiting on finalized OASIS review.',
      },
    ],
    escalation_note: 'Claim release is waiting on finalized OASIS review.',
    last_escalated_at: '2026-04-21 09:15:00',
    due_at: '2026-04-20 12:00:00',
  },
  {
    id: 2,
    episode_id: 1,
    task_type: 'claim_hold',
    priority: 'medium',
    status: 'open',
    title: 'Release NOA after SOC chart review',
    details: 'NOA can submit after QA confirms SOC documentation completeness.',
    assigned_role: 'Billing',
    assigned_user_name: 'Bianca Billing',
    due_at: '2026-04-23 12:00:00',
  },
]

const securitySettings: SecuritySettings = {
  id: 1,
  require_mfa: true,
  session_timeout_minutes: 30,
  remember_device_days: 14,
  password_rotation_days: 90,
  attachment_retention_days: 365,
  allowed_ip_ranges: '10.24.0.0/16\n192.168.10.0/24',
  enforce_device_attestation: true,
}

const auditEvents: AuditEvent[] = [
  {
    id: 1,
    actor_email: 'intake@harborhomehealth.test',
    action: 'referral_converted',
    model: 'Episode',
    model_id: 1,
    details: {
      referral_id: 1,
      patient_name: 'Eleanor Bishop',
    },
    created: '2026-04-19 08:20:00',
  },
  {
    id: 2,
    actor_email: 'clinical@harborhomehealth.test',
    action: 'episode_activated',
    model: 'Episode',
    model_id: 1,
    details: {
      noa_due_date: '2026-04-24',
      pdgm_group_code: 'MMTA-CARDIAC-INSTITUTIONAL-EARLY-MEDIUM-LOW',
    },
    created: '2026-04-19 10:10:00',
  },
  {
    id: 3,
    actor_email: 'billing@harborhomehealth.test',
    action: 'claim_submitted',
    model: 'Claim',
    model_id: 2,
    details: {
      claim_type: 'episode',
      amount: 2480,
    },
    created: '2026-04-21 14:05:00',
  },
]

const adminUsers: AppUser[] = [
  {
    id: 1,
    full_name: 'Marina Intake',
    email: 'intake@harborhomehealth.test',
    role: 'Intake',
    mobile: '404-555-0199',
    status: 'active',
    mfa_enabled: true,
    last_login_at: '2026-04-29 08:05:00',
  },
  {
    id: 2,
    full_name: 'Nina Clinician',
    email: 'clinician@harborhomehealth.test',
    role: 'Clinician',
    mobile: '404-555-0177',
    status: 'active',
    mfa_enabled: false,
    last_login_at: '2026-04-29 07:40:00',
  },
  {
    id: 3,
    full_name: 'Bianca Billing',
    email: 'billing@harborhomehealth.test',
    role: 'Billing',
    mobile: '404-555-0166',
    status: 'active',
    mfa_enabled: true,
    last_login_at: '2026-04-29 09:25:00',
  },
  {
    id: 4,
    full_name: 'Quinn QA Reviewer',
    email: 'qa@harborhomehealth.test',
    role: 'QA',
    mobile: '404-555-0155',
    status: 'suspended',
    mfa_enabled: true,
    last_login_at: '2026-04-26 16:10:00',
  },
]

const sessionActivity: SessionActivity[] = [
  {
    user_id: 3,
    full_name: 'Bianca Billing',
    email: 'billing@harborhomehealth.test',
    role: 'Billing',
    status: 'active',
    mfa_enabled: true,
    last_login_at: '2026-04-29 09:25:00',
    activity_state: 'active_window',
    recent_action: 'claim_submitted',
    recent_model: 'Claim',
    recent_at: '2026-04-21 14:05:00',
  },
  {
    user_id: 1,
    full_name: 'Marina Intake',
    email: 'intake@harborhomehealth.test',
    role: 'Intake',
    status: 'active',
    mfa_enabled: true,
    last_login_at: '2026-04-29 08:05:00',
    activity_state: 'active_window',
    recent_action: 'referral_converted',
    recent_model: 'Episode',
    recent_at: '2026-04-19 08:20:00',
  },
  {
    user_id: 2,
    full_name: 'Nina Clinician',
    email: 'clinician@harborhomehealth.test',
    role: 'Clinician',
    status: 'active',
    mfa_enabled: false,
    last_login_at: '2026-04-29 07:40:00',
    activity_state: 'active_window',
    recent_action: 'episode_activated',
    recent_model: 'Episode',
    recent_at: '2026-04-19 10:10:00',
  },
  {
    user_id: 4,
    full_name: 'Quinn QA Reviewer',
    email: 'qa@harborhomehealth.test',
    role: 'QA',
    status: 'suspended',
    mfa_enabled: true,
    last_login_at: '2026-04-26 16:10:00',
    activity_state: 'stale_window',
    recent_action: 'oasis_review',
    recent_model: 'Assessment',
    recent_at: '2026-04-21 09:15:00',
  },
]

export function createDemoDataset(): AppDataset {
  return {
    metrics: {
      patients: patients.length,
      referrals: referrals.length,
      episodes: episodes.length,
      visitsToday: visits.filter((visit) => visit.scheduled_start.startsWith('2026-04-19')).length,
      qaTasks: qaTasks.filter((task) => task.status === 'open').length,
      claimsOnHold: claims.filter((claim) => Boolean(claim.hold_reason)).length,
    },
    patients: structuredClone(patients),
    referrals: structuredClone(referrals),
    referralDocuments: structuredClone(referralDocuments),
    physicianOrders: structuredClone(physicianOrders),
    episodes: structuredClone(episodes),
    assessments: structuredClone(assessments),
    visits: structuredClone(visits),
    evvRecords: structuredClone(evvRecords),
    claims: structuredClone(claims),
    qaTasks: structuredClone(qaTasks),
    securitySettings: structuredClone(securitySettings),
    auditEvents: structuredClone(auditEvents),
    adminUsers: structuredClone(adminUsers),
    sessionActivity: structuredClone(sessionActivity),
  }
}
